config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#_new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'addcourses' => 'courses#new'
  get "courses/sort" => "courses#sort", as: :sort
  get 'courses/enroll/:id' => 'courses#enroll', as: :courses_enroll
  get 'courses/unenroll/:id' => 'courses#unenroll', as: :courses_unenroll
  get 'courses/interested/:id' => 'courses#interested', as: :interested

  get 'courses/myclasses' => 'users#user_classes', as: :user_classes

  resources :users
  resources :courses do
    resources :reviews
  end

  namespace :api do
    resources :courses, only: [:index, :show]
  end

end

app/controllers/API/courses_controller.rb
module API
  class CoursesController < ApplicationController

    def index
      render json: Course.all
    end

     def show
      render json: Course.find(params[:id])
    end

  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # code below is used to set the sort status
  @@descending = false

  # creates a new course
  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:success] = "Course Added"
      redirect_to @course
    else
      render 'new'
    end
  end

  # adds kaminari paginator
  def index
    if params[:query] && params[:search]
      @paginate = false
      search_by = params[:search].to_sym
      query = params[:query]
      course_list = Course.all
      @courses = []
      course_list.each do |course|
        if course[search_by].to_s.downcase.include? params[:query].to_s.downcase
          @courses << course
        end
      end
    else
      @paginate = true
      @courses = Course.page(params[:page]).per(10).padding(0)
    end
  end

  # shows individual classes as well as adds kaminari pagination to class pages
  def show
    if params[:commit] == "next class"
        course = Course.find(params[:id].to_i + 1)
        redirect_to course_path(course)
    elsif params[:commit] == "prev class"
        course = Course.find(params[:id].to_i - 1)
        redirect_to course_path(course)
    else
        @course = Course.find(params[:id])
    end
  end

  # sorts classes on main class page
  def sort
    if @@descending
      @courses = Course.order(params[:order_by] + ' DESC')
      @@descending = false
    else
      @courses = Course.order(params[:order_by])
      @@descending = true
    end
    render :index
  end

  # selects which class to edit and allows params to be updated
  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(course_params)
      flash[:success] = "Course Updated"
      redirect_to @course
    else
      render 'edit'
    end
  end

  # selects the current user based on the id of the session and the id of the user; they should match
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # wanted to implement the below so that the user could select that they were interested in the course but maybe enroll at a later date
  # def interested
  #   course = Course.find(params[:id])
  #   user = current_user
  #   flash[:success] = "I see you're interested."
  #   redirect_to courses_path
  # end

  # allows the user to enroll in a course; addes the user to the course users database
  def enroll
    course = Course.find(params[:id])
    user = current_user
    if course.users.where(:id => user.id).any? #check if student is in course
        flash[:danger] = "You are already enrolled in this course." #if student is in course then dont allow enrollment
        redirect_to courses_path
    else #if not signed up allow
        course.users << user
        flash[:success] = "Successfully Enrolled"
        redirect_to courses_path(course)
    end
  end

  # allows the user to unenroll from the course by deleting the users id from the course database
  def unenroll
    course = Course.find(params[:id])
    user = current_user
    if course.users.where(:id => user.id).any? #check if student is in course, if true:
      course.users.delete(user.id) #remove user id from course (remove item from ruby array)
      course.save #resave course
      flash[:success] = "Successfully Unenrolled"
    else #if student is not enrolled in the course
      flash[:danger] = "You are not enrolled in this course."
    end
      redirect_to courses_path(course)
  end

  # deletes a course
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end

private
  # defines the params that are particulare to creating a course; these are defined by the schema which was created when the course model was created
  def course_params
    params.require(:course).permit(:name, :instructor, :street_address, :zip_code, :course_image_url, :sessions_per_course, :start_date, :end_date, :course_day_of_week, :description, :price, :creator_id)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.erb
<!-- form for editing course info -->
<% provide(:title, "Edit Class") %>
<h1>update class information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@course) do |f| %>

      <%= f.label :name, "Class Name" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :instructor %>
      <%= f.text_field :instructor, class: 'form-control' %>

      <%= f.label :street_address %>
      <%= f.text_field :street_address, class: 'form-control' %>

      <%= f.label :zip_code %>
      <%= f.number_field :zip_code, class: 'form-control' %>

      <%= f.label :course_image_url, "Class Image (URL)" %>
      <%= f.url_field :course_image_url, class: 'form-control' %>

      <%= f.label :sessions_per_course, "Number of Sessions" %>
      <%= f.text_field :sessions_per_course, class: 'form-control' %>

      <%= f.label :start_date %>
      <%= f.date_field :start_date, class: 'form-control' %>

      <%= f.label :end_date %>
      <%= f.date_field :end_date, class: 'form-control' %>

      <%= f.label :start_time %>
      <%= f.text_field :start_time, class: 'form-control' %>

      <%= f.label :end_time %>
      <%= f.text_field :end_time, class: 'form-control' %>

      <%= f.label :course_day_of_week, "Class Held On (Day of Week)" %>
      <%= f.text_field :course_day_of_week, class: 'form-control' %>

      <%= f.label :description, "Class Description" %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :price %>
      <%= f.number_field :price, :class => 'price', :value => (number_to_currency(f.object.price, :precision => 2) || 0) %>

    <%= f.submit "save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/courses/index.html.erb
<!-- this page shows all the classes offered on palette -->
<% provide(:title, 'Classes') %>
<h1>classes available</h1>

<%= form_tag(courses_path, method: 'get') do %>
<!-- search tools -->
<div class="row">
    <div class="col-md-4">
        <%= select_tag "search", options_for_select([["Class Name", "name"], ["Instructor Name", "instructor"], ["Zip Code", "zip_code"]]), "class" => "select-search select-div" %>
    </div>
    <div class="col-md-4">
        <%= text_field_tag :query, nil, placeholder: 'Enter search term...', "class" => "select-search"  %>
    </div>
    <div class="col-md-4">
        <%= submit_tag "search", "class" => "btn btn-primary", "id" => "btn-search"%>
    </div>
<% end %>
</div>

<!-- table with courses listed and sort functionality -->
<div class="container">
<table class="table">
    <tr>
        <th></th>
        <th><%= link_to "Course", sort_url(order_by: "name") %></th>
        <th><%= link_to "Instructor", sort_url(order_by: "instructor") %></th>
        <th><%= link_to "Location", sort_url(order_by: "zip_code") %></th>
        <th><%= link_to "Held On", sort_url(order_by: "course_day_of_week") %></th>
        <th><%= link_to "Start Date", sort_url(order_by: "start_date") %></th>
        <th><%= link_to "End Date", sort_url(order_by: "end_date") %></th>
        <th><%= link_to "Sessions", sort_url(order_by: "sessions_per_course") %></th>
        <th><%= link_to "Price", sort_url(order_by: "price") %></th>
        <% if logged_in? %>
<!--             <th><%= link_to "Interested", "#" %></th>
 -->        <th><%= link_to "Enroll", "#" %></th>
            <th><%= link_to "Unenroll", "#" %></th>
        <% end %>
    </tr>
    <% @courses.each do |course| %>
    <tr>
        <td><%= link_to image_tag(course.course_image_url, :class => "thumbnail-image img-rounded"), course_path(course)%></td>
        <td><%= link_to course.name, course_path(course) %></td>
        <td><%= course.instructor %></td>
        <td><%= course.zip_code %></td>
        <td><%= course.course_day_of_week %></td>
        <td><%= course.start_date.strftime("%m/%d/%Y") %></td>
        <td><%= course.end_date.strftime("%m/%d/%Y") %></td>
        <td><%= course.sessions_per_course %></td>
        <td><%= number_to_currency(course.price) %></td>
        <% if logged_in? %>
<!--             <td><%= link_to 'interested', interested_path(course), :class => "btn btn-primary"%></td> -->
            <td><%= link_to 'enroll', courses_enroll_path(course), :class => "btn btn-primary btn-enroll toggle", :id=>"enroll-toggle"%></td>
            <td><%= link_to 'unenroll', courses_unenroll_path(course), :class => "btn btn-primary btn-enroll" %></td>
        <% end %>
    </tr>
    <% end %>
</table>
</div>
<% if @paginate %>
  <%= paginate @courses %>
<% end %>


<!-- // $("#enroll-toggle").click(function(){
//     $(".toggle").toggle();
// }); -->

app/views/courses/new.html.erb
<!-- allows a user to create a new class -->
<% provide(:title, 'Add a Course') %>
<h1>create a class</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @course do |f| %>

      <%= f.label :name, "Class Name" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :instructor %>
      <%= f.text_field :instructor, class: 'form-control' %>

      <%= f.label :street_address %>
      <%= f.text_field :street_address, class: 'form-control' %>

      <%= f.label :zip_code %>
      <%= f.number_field :zip_code, class: 'form-control' %>

      <%= f.label :course_image_url, "Course Image (URL)" %>
      <%= f.url_field :course_image_url, class: 'form-control' %>

      <%= f.label :sessions_per_course, "Number of Sessions" %>
      <%= f.text_field :sessions_per_course, class: 'form-control' %>

      <%= f.label :start_date %>
      <%= f.date_field :start_date, class: 'form-control' %>

      <%= f.label :end_date %>
      <%= f.date_field :end_date, class: 'form-control' %>

      <%= f.label :start_time %>
      <%= f.text_field :start_time, class: 'form-control' %>

      <%= f.label :end_time %>
      <%= f.text_field :end_time, class: 'form-control' %>

      <%= f.label :course_day_of_week, "Class Held On (Day of Week)"  %>
      <%= f.text_field :course_day_of_week, class: 'form-control' %>

      <%= f.label :description, "Class Description" %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :price %>
      <%= f.number_field :price, :class => 'price', :value => (number_to_currency(f.object.price, :precision => 2) || 0) %>

      <%= f.hidden_field :creator_id, :value => current_user.id %>

      <%= f.submit "create course", class: "btn btn-primary", id: "btn-submit" %>
    <% end %>
  </div>
</div>

app/views/courses/show.html.erb
<div class="container">
  <!-- shows individual courses -->
  <% provide(:title, @course.name) %>
  <div class="row">
    <h1><%= @course.name.downcase %></h1>
    <% if logged_in? %>
      <% if current_user.id == @course.creator_id %>
        <h5><%= link_to "edit class", edit_course_path%> &nbsp;&nbsp;&nbsp;<%= link_to "delete class", course_path, method: :delete, data: { confirm: "You sure?" } %></h5>
      <% end %>
    <% end %>
  </div>
  <div class="row">
    <div class ="center course-description col-md-8">
      <h3><%= @course.description %></h3>
      <h3>Instructor: <%= @course.instructor %></h3>
    </div>
    <div class ="col-md-1">
    </div>
    <div class ="center course-image col-md-3">
      <h3><%= image_tag(@course.course_image_url, :class => "thumbnail-image img-rounded")%></h3>
    </div>
  </div>
  <div class="row">
    <div class ="center course-address col-md-4">
      <h3>Located at <%= @course.street_address %></h3>
      <iframe width="250" height="150" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCkJwN8UYx38_JWe-A8-c79krZCpmkBOYI&q=<%=@course.street_address%>" allowfullscreen class="iframe"></iframe>
    </div>
    <div class ="col-md-1">
    </div>
    <div class ="center course-time col-md-3">
      <h3><%= @course.course_day_of_week %></h3>
      <h3><%= @course.start_date.strftime("%m/%d/%Y") %></h3>
      <h3>to</h3>
      <h3><%= @course.end_date.strftime("%m/%d/%Y") %></h3>
    </div>
    <div class ="col-md-1">
    </div>
    <div class ="center course-price col-md-3">
      <h3>Class Fee</h3>
      <h3><%= number_to_currency(@course.price) %></h3>
    </div>
    <div class ="col-md-1">
    </div>
    <% if logged_in? %>
      <div class ="center course-enroll col-md-3">
          <% if !@course.users.where(:id => current_user.id).any?  %>
            <%= link_to 'enroll', courses_enroll_path(@course), :class => "btn btn-primary", :id => "btn-enroll"%>
          <% end %>
          <% if @course.users.where(:id => current_user.id).any?  %>
            <%= link_to 'unenroll', courses_unenroll_path(@course), :class => "btn btn-primary", :id => "btn-enroll" %>
          <% end %>
      </div>
  </div>
  <div class="row">
    <div class="center jumbotron col-md-12">
      <h3>reviews</h3>
      <%= render 'reviews/new' %>
      <table class ="table">
        <thead>
          <tr>
          </tr>
        </thead>
        <% @course.reviews.each do |review| %>
        <tbody>
          <tr>
            <td><%= link_to User.find_by(:id => review.user_id).name, user_path(User.find_by(:id => review.user_id).id)%></td>
            <td><%= review.content%></td>
            <td>
            <% if current_user.id == review.user_id %>
              <%= link_to "edit review", edit_course_review_path(@course.id, review.id), :class => "btn btn-primary review" %>
              <%= link_to "delete review", course_review_path(@course.id, review.id), method: :delete, :class => "btn btn-primary review"%>
            <% end %>
            </td>
          </tr>
        </tbody>
      <% end %>
      </table>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div class = "center prev-next">
      <%= form_tag(course_path, method: "get") do %>
          <%= submit_tag "prev class", "class" => "btn btn-primary btn-prev" %>
          <%= submit_tag "next class", "class" => "btn btn-primary btn-next" %>
      <% end %>
    </div>
  </div>
</div>