config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#_new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'addcourses' => 'courses#new'
  get "courses/sort" => "courses#sort", as: :sort
  get 'courses/enroll/:id' => 'courses#enroll', as: :courses_enroll
  get 'courses/unenroll/:id' => 'courses#unenroll', as: :courses_unenroll
  get 'courses/interested/:id' => 'courses#interested', as: :interested

  get 'courses/myclasses' => 'users#user_classes', as: :user_classes

  resources :users
  resources :courses do
    resources :reviews
  end

  namespace :api do
    resources :courses, only: [:index, :show]
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <h6>
    Palette | Art &amp; Design Classes in Los Angeles, CA
  </h6>
  <nav>
    <ul>
      <li><%= link_to "http://facebook.com", :target => "_blank" do%><i class="fa fa-facebook"></i></li><% end %>
      <li><%= link_to "http://twitter.com", :target => "_blank" do%><i class="fa fa-twitter"></i></li><% end %>
      <li><%= link_to "http://pinterest.com", :target => "_blank" do%><i class="fa fa-pinterest"></i></li><% end %>
      <li><%= link_to "http://instagram.com", :target => "_blank" do%><i class="fa fa-instagram"></i></li><% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-fixed-top navbar-inverse " role="navigation">
  <div class="container-fluid">
    <%= link_to "P A L E T T E", root_path, id: "logo" %>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
          <% if !logged_in? %>
            <li><%= link_to "about", about_path %></li>
            <li><%= link_to "contact", contact_path %></li>
            <li><%= link_to "classes", courses_path %></li>
            <% end %>
          <% if logged_in? %>
            <li><%= link_to "about", about_path %></li>
            <li><%= link_to "contact", contact_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  classes <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "all classes", courses_path, class: "d-list" %></li>
                <li><%= link_to "my classes", user_classes_path, class: "d-list" %></li>
                <li class="divider"></li>
                <li><%= link_to "create a class", addcourses_path, class: "d-list" %></li>
              </ul>
            <li><%= link_to "users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "profile", root_path, class: "d-list" %></li>
                <li><%= link_to "settings", edit_user_path(current_user), class: "d-list" %></li>
                <li class="divider"></li>
                <li><%= link_to "log out", logout_path, method: "delete", class: "d-list" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'log in', login_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#loginModal', 'data-type' => "html" } %></li>
          <% end %>
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- FAVICON -->
  <%= favicon_link_tag 'https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_palette_48px-128.png' %>
  <!-- GOOGLEFONTS -->
    <link href='https://fonts.googleapis.com/css?family=Cardo:400,700|Montserrat:400,700' rel='stylesheet' type='text/css'>
  <!-- FONTAWESOME ICONS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <!-- BOOTSTRAP -->
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"> </script>
  </head>
  <body id="bootstrap-overrides">
<!--   <%= render partial: "shared/flash_messages", flash: flash %>
 -->    <!-- Login Modal -->
    <div class="modal fade" id="loginModal" role="dialog" aria-labelledby="myModalLabel"  aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4>log in</h4>
                </div>
                <div class="row">
                  <div class="col-md-6 col-md-offset-3">
                    <%= render 'sessions/new'%>
                  </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End of Modal -->
    <!-- Sign Up Modal -->
    <div class="modal fade" id="signupModal" role="dialog" aria-labelledby="myModalLabel"  aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4>sign up</h4>
                </div>
                <div class="row">
                  <div class="col-md-6 col-md-offset-3">
                    <%= render 'users/new'%>
                  </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End of Modal -->

    <!-- End of Modal -->
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>